name: Passing Data Between Steps

on:
  workflow_dispatch:

jobs:
  data-passing:
    runs-on: ubuntu-latest
    steps:
      - name: create data
        id: sender

        run: |
          echo  "name=Michal"  >> $GITHUB_OUTPUT

      - name: Recieve data
        run: |
          echo ${{ steps.sender.outputs.name }}