name: 12 Pat Bump tag

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: ${{ github.event.pull-request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull-request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          WITH_V: true
    